### ISSUE TITLE
Shouldn't method kern be a private method?

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/Font-AFM-raku#11]

**Comment by dwarring** [comment]
The `kern` method is directly used by [PDF::Content::Text::Box](https://github.com/pdf-raku/PDF-Content-raku/blob/e6a5371ed4cebb5d35fa08b63fc9bab0f35451d7/lib/PDF/Content/Text/Box.rakumod#L84). For example:
```
my PDF::Lite $pdf .= new;
my $gfx = $pdf.add-page.gfx;
my $font = $pdf.core-font( :family<Helvetica> );
$gfx.say('Hello World', :kern, :position[50, 100], :$font);
```
This causes kerning between `W` and `o`.

**Comment by tbrowder** [comment]
Ah, I see. Thanks.

**Comment by tbrowder** [comment]
Hm, not directly, isn't that a Bool saying to kern the result?

**Comment by tbrowder** [comment]
Overcome by more familiarity.
