### ISSUE TITLE
IsFixedPitch returns 'false' or 'true', not a true Boolean for Perl 6

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/Font-AFM-raku#4]
I had to do a work-around when I found the return value wasn't changing between Courier and Times-Roman with this test:

my $a = Font::AFM.new: :name<Courier>;
my $b = Font::AFM.new: :name<Times-Roman>;
say $a.IsFixedPitch; #  true [a string, not a Boolean]
say $b.IsFixedPitch; #  false [a string, not a Boolean]
for $a, $b -> $f {
    say "true" if $f.IsFixedPitch;
}
# output
true
true

Update:

After reading the docs more closely, I see that the return value is supposed to be 'true' (or 'false'), but I think a Boolean return of True or False would be better (and safer).

Update 2

I should have started off with telling you how much I appreciate this module!  I used it very heavily for PS work in Perl 5 and I'm glad to have a Perl 6 version because I'm trying to write all code in Perl 6 now.

Thank you!

**Comment by dwarring** [comment]
@tbrowder - please try again with latest Font::AFM

**Comment by tbrowder** [comment]
Will do and report, thanks.

**Comment by dwarring** [comment]
OK after applying #5 and fixing with 7d78282
