### ISSUE TITLE
Font metrics for Zapfdingbats not found

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/Font-AFM-raku#6]
When testing a pdf creation program I iterated over the 14 core fonts and tried to get both the pdf font object and its corresponding metrics object for each. All attempts were successful except for the Zaphdingbats: its font object was succesfully obtained BUT the metrics object was not:

 ~~~
my $afm = Font::AFM.new: :name<Zapfdingbats>;
Can't find the AFM file for Zapfdingbats (Zapfdingbats.afm)
  in method load-afm-metrics at /home/tbrowde/.raku/sources/71E60D8F710457D56668C01B4743FB3D93178B9D (Font::AFM) line 263
  in submethod TWEAK at /home/tbrowde/.raku/sources/71E60D8F710457D56668C01B4743FB3D93178B9D (Font::AFM) line 207
  in block  at ./fonts.raku line 21
  in block <unit> at ./fonts.raku line 19
~~~

The program I used for testing is in the dev subdirectory of my PDF::Document repo at <https://github.com/tbrowder/PDF-Document>

**Comment by dwarring** [comment]
I think the README and doco for Font::AFM is pretty misleading (and that error message isn't great).

`Font::AFM.new: :$name` is scanning the users system font directories for the given font,

If all you want is metrics for the core PDF fonts, there's some prebuilt classes for that: Font::Metrics::zapfdingbats,  Font::Metrics::courier, etc.

These are listed in the README.

**Comment by dwarring** [comment]
It could also be useful to have a method `Font::AFM.core-font('Zapfdingbats')` or some-such to access these.

**Comment by dwarring** [comment]
Ah, sorry, there is already a `core-font` method which IS being called and from PDF::Content::Font::CoreFont.

Leave it with me.

**Comment by dwarring** [comment]
Have put in a [PR](https://github.com/tbrowder/PDF-Document/pull/1) to use the core-font method.

The Font::AFM README doesn't even mention this method and could generally do with some TLC.

**Comment by dwarring** [comment]
Font::AFM 1.24.3 has been uploaded to CPAN with documentation updates, including:

- Include `core-font()` example in synopsis
- Change misleading documentation for `new()`. Now describes what this method really does (scan you local system for matching fonts. This is probably a fairly archaic thing to do in 2020).
- Mention Font::FreeType and HarfBuzz which can be used to obtain font metrics for other fonts.
