### ISSUE TITLE
Font::AFM doesn't respect the existing "METRICS" environment variable

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/Font-AFM-raku#9]
I tried using a "METRICS" environment variable set to "/usr/share/afm" during Github workflow testing but the files I placed there **were not found**. However, when I put the files in "/usr/lib/afm" they **were** found.

**Comment by dwarring** [comment]
I've added tests with https://github.com/pdf-raku/Font-AFM-raku/commit/69c357a1cb1a315181833c113e4e129549cfef88 and fixed a bug when .afm is appended to the font name with .https://github.com/pdf-raku/Font-AFM-raku/commit/e05248e83d3bfdd555088c1ec68cd510820d2ff7.

Not sure if I've squashed this bug. The matching of the font to file name is currently case sensitive, which could be an issue.

**Comment by tbrowder** [comment]
This works for me now. Thanks!
